### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by IntegralCoCo** [jpthu17/HBI#2]
您好，我想请问您会在近期放一个arxiv吗，我对您的论文非常感兴趣，如果可以的话希望可以尽快阅读到您的著作，感谢！

**Comment by jpthu17** [comment]
感谢您对我们工作的关注，我们会尽快整理完camera ready版本，预计在3月20号左右上传arxiv，谢谢！

**Comment by jpthu17** [comment]
Our paper is available at https://arxiv.org/abs/2301.00184.
